[tool.commitizen]
name = "cz_conventional_commits"
version = "0.0.21"
tag_format = "$version"
version_files = [
    "main.py:__version__",
    ".cz.toml:version"
]
update_changelog_on_bump = true
major_version_zero = true
