# -*- coding: utf-8 -*-
"""update websocket2

Revision ID: 61ffe6f9cf81
Revises: add41f59305f
Create Date: 2025-03-07 16:17:52.102296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "61ffe6f9cf81"
down_revision: Union[str, None] = "add41f59305f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "websocket_notification",
        sa.Column("count_max_capacity", sa.Integer(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("websocket_notification", "count_max_capacity")
    # ### end Alembic commands ###
