# -*- coding: utf-8 -*-
"""initial migration

Revision ID: 8c20258b267a
Revises: 4b8f94fb2724
Create Date: 2025-01-26 13:33:10.455482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8c20258b267a"
down_revision: Union[str, None] = "4b8f94fb2724"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # op.add_column(
    #    "cameras", sa.Column("ultima_modificacao", sa.DateTime(), nullable=True)
    # )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cameras", "ultima_modificacao")
    # ### end Alembic commands ###
