# -*- coding: utf-8 -*-
"""update websocket channelds

Revision ID: 8ec545a5b7d6
Revises: 61ffe6f9cf81
Create Date: 2025-03-10 09:46:27.496700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8ec545a5b7d6"
down_revision: Union[str, None] = "61ffe6f9cf81"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "websocket_notification",
        sa.Column("channel_ids", sa.ARRAY(sa.UUID()), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("websocket_notification", "channel_ids")
    # ### end Alembic commands ###
