# -*- coding: utf-8 -*-
"""update websocket

Revision ID: add41f59305f
Revises: c3193361f801
Create Date: 2025-03-07 16:14:27.420904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "add41f59305f"
down_revision: Union[str, None] = "c3193361f801"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "websocket_notification", sa.Column("total_in", sa.Integer(), nullable=True)
    )
    op.add_column(
        "websocket_notification", sa.Column("total_out", sa.Integer(), nullable=True)
    )
    op.add_column(
        "websocket_notification",
        sa.Column("label", sa.ARRAY(sa.String()), nullable=False),
    )
    op.add_column(
        "websocket_notification",
        sa.Column("count_in", sa.ARRAY(sa.Integer()), nullable=True),
    )
    op.add_column(
        "websocket_notification",
        sa.Column("count_out", sa.ARRAY(sa.Integer()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("websocket_notification", "count_out")
    op.drop_column("websocket_notification", "count_in")
    op.drop_column("websocket_notification", "label")
    op.drop_column("websocket_notification", "total_out")
    op.drop_column("websocket_notification", "total_in")
    # ### end Alembic commands ###
