# -*- coding: utf-8 -*-
"""add colun date

Revision ID: c3193361f801
Revises: 576c438bb1e6
Create Date: 2025-03-03 16:30:40.294507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c3193361f801"
down_revision: Union[str, None] = "576c438bb1e6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("count_maximun_capacity", sa.Column("date", sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("count_maximun_capacity", "date")
    # ### end Alembic commands ###
