# -*- coding: utf-8 -*-
"""add timstamp

Revision ID: c75c1feeef15
Revises: 8c20258b267a
Create Date: 2025-02-25 08:49:22.004282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c75c1feeef15"
down_revision: Union[str, None] = "8c20258b267a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "event_count", sa.Column("timestamp", postgresql.TIMESTAMP(), nullable=True)
    )
    op.alter_column(
        "event_count_temp",
        "event_time",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=postgresql.TIMESTAMP(precision=4),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "event_count_temp",
        "event_time",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=postgresql.TIMESTAMP(precision=5),
        existing_nullable=True,
    )
    op.drop_column("event_count", "timestamp")
    # ### end Alembic commands ###
