# -*- coding: utf-8 -*-
"""update websocket

Revision ID: edbdf1ee184b
Revises: 8ec545a5b7d6
Create Date: 2025-03-10 13:52:34.665286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "edbdf1ee184b"
down_revision: Union[str, None] = "8ec545a5b7d6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "websocket_notification", sa.Column("meta_data", sa.JSON(), nullable=True)
    )
    op.drop_column("websocket_notification", "channel_ids")
    op.drop_column("websocket_notification", "total_out")
    op.drop_column("websocket_notification", "label")
    op.drop_column("websocket_notification", "count_in")
    op.drop_column("websocket_notification", "count_out")
    op.drop_column("websocket_notification", "total_in")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "websocket_notification",
        sa.Column("total_in", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "websocket_notification",
        sa.Column(
            "count_out",
            postgresql.ARRAY(sa.INTEGER()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "websocket_notification",
        sa.Column(
            "count_in",
            postgresql.ARRAY(sa.INTEGER()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "websocket_notification",
        sa.Column(
            "label", postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "websocket_notification",
        sa.Column("total_out", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "websocket_notification",
        sa.Column(
            "channel_ids",
            postgresql.ARRAY(sa.UUID()),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("websocket_notification", "meta_data")
    # ### end Alembic commands ###
