---
name: Build, Test, and Deploy to AWS ECR

on:
    push:
        branches:
            - main

jobs:
    build-test-deploy:
        name: Build, Test, and Deploy
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: 3.10.11

            - name: Install Dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  pip install pytest

            - name: Run Tests
              run: |
                  pytest tests

            - name: Log in to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v2
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  AWS_REGION: sa-east-1

            - name: Build Docker Image
              run: |
                  docker build -t smartflux_api .

            - name: Tag Docker Image
              run: |
                  docker tag smartflux_api:latest 856246847280.dkr.ecr.sa-east-1.amazonaws.com/smartflux/smartflux_api:latest

            - name: Push to Amazon ECR
              run: |
                  docker push 856246847280.dkr.ecr.sa-east-1.amazonaws.com/smartflux/smartflux_api:latest
